"""
Django settings for callyourmedic project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%wsfg43xfa!*d!c*c7ucl!4j$hc766mmhzv1w6@1oopje3lu=1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['localhost', '127.0.0.1',]
#ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'rest_framework.authtoken',
    'rest_framework',
    'widget_tweaks',
    'storages',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # custom apps
    'organisations',
    'addresses',
    'hospitals',
    'doctors',
    'patients',
    'marketplace',
    'uploads',
    #'transactions',
    #util apps
    'utils',
    'mailer',
    #cymportal
    'cymportal',
    'webportal',
    'webapi',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]

ROOT_URLCONF = 'callyourmedic.urls'

# Template settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                    BASE_DIR + '/templates',
                    BASE_DIR + '/cymportal/templates',
                    BASE_DIR + '/cymportal/templates/views',
                    BASE_DIR + '/cymportal/templates/views/dashboard',
                    BASE_DIR + '/cymportal/templates/views/org',
                    BASE_DIR + '/cymportal/templates/views/usr',
                    BASE_DIR + '/cymportal/templates/views/marketplace',
                    BASE_DIR + '/webportal/templates',
                    BASE_DIR + '/webportal/templates/views/dashboard',
                    BASE_DIR + '/webportal/templates/views/org',
                    BASE_DIR + '/webportal/templates/views/usr',
                    BASE_DIR + '/webportal/templates/views/hospital',
                    BASE_DIR + '/webportal/templates/views/doctor',
                    BASE_DIR + '/webportal/templates/views/patient',
                    BASE_DIR + '/mailer/templates/',
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'callyourmedic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'medicalldb',
#         'USER': 'postgres',
#         'PASSWORD': 'admin123',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'medicalldb',
        'USER': 'apoorv',
        'PASSWORD': 'admin123',
        'HOST': 'postgresql-medicall-instance.ckzsmmruhp4x.ap-southeast-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files settings

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    # ('assets','/Volumes/Apoorv/MyWork/django/callyourmedic_app/callyourmedic/static'),
    #('assets',BASE_DIR + '/static/assets'),
    BASE_DIR + '/resources',
    
)

STATIC_ROOT = BASE_DIR + '/static'

AWS_ACCESS_KEY_ID = 'AKIAJU7LWHYCQZVTM6PA'
AWS_SECRET_ACCESS_KEY = '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'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
AWS_STORAGE_BUCKET_NAME = 'callyourmedic-resources-bucket'
AWS_HEADERS = {
    'Cache-Control': 'max-age=86400',
}
AWS_QUERYSTRING_AUTH = False


# Log settings
LOGGING = {
    'version' : 1,
    'disable_existing_loggers' : True,
    'formatters' : {
        'standard' : {
            'format' : '[%(process)d %(processName)s] [%(asctime)s] [%(levelname)s] [%(name)s | %(funcName)s] : %(message)s'
        },
    },
    'handlers' : {
        'default' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : BASE_DIR + '/logs/default.log',
            'maxBytes' : 1024 * 1024 * 5, #5MB
            'backupCount' : 5,
            'formatter' : 'standard',
        },
        'cym_handler' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : BASE_DIR + '/logs/cym.log',
            'maxBytes' : 1024 * 1024 * 5, #5MB
            'backupCount' : 5,
            'formatter' : 'standard',
        },
        'webportal_handler' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : BASE_DIR + '/logs/webportal.log',
            'maxBytes' : 1024 * 1024 * 5, #5MB
            'backupCount' : 5,
            'formatter' : 'standard',
        },
        'request_handler' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : BASE_DIR + '/logs/request_handler.log',
            'maxBytes' : 1024 * 1024 * 5, #5MB
            'backupCount' : 5,
            'formatter' : 'standard',
        },
        'api_handler' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : BASE_DIR + '/logs/api_logger.log',
            'maxBytes' : 1024 * 1024 * 5, #5MB
            'backupCount' : 5,
            'formatter' : 'standard',
        },
        'mail_handler' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : BASE_DIR + '/logs/mail_logger.log',
            'maxBytes' : 1024 * 1024 * 5, #5MB
            'backupCount' : 5,
            'formatter' : 'standard',
        },
        'tasks_handler' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : BASE_DIR + '/logs/tasks_logger.log',
            'maxBytes' : 1024 * 1024 * 5, #5MB
            'backupCount' : 5,
            'formatter' : 'standard',
        },
    },
    'loggers' : {
        '' : {
            'handlers' : ['default'],
            'level' : 'DEBUG',
            'propagate' : True,
        },
        'django.request' : {
            'handlers' : ['request_handler'],
            'level' : 'DEBUG',
            'propagate' : False,
        },
        'cym' : {
            'handlers' : ['cym_handler'],
            'level' : 'DEBUG',
            'propagate' : True,
        },
        'webportal' : {
            'handlers' : ['webportal_handler'],
            'level' : 'DEBUG',
            'propagate' : True,
        },
        'webapi' : {
            'handlers' : ['api_handler'],
            'level' : 'DEBUG',
            'propagate' : True,
        },
        'mail' : {
            'handlers' : ['mail_handler'],
            'level' : 'DEBUG',
            'propagate' : True,
        },
        'tasks' : {
            'handlers' : ['tasks_handler'],
            'level' : 'DEBUG',
            'propagate' : True,
        },
    }
}

# Cache settings
CACHES = { 'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION' : 'cache-store'
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'


REST_FRAMEWORK = {

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ]
}

# Email settings

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'support@callyourmedic.com'
EMAIL_HOST_PASSWORD = 'birth@3107'
EMAIL_PORT = 587

# Celery settings

BROKER_TRANSPORT = 'sqs'
BROKER_TRANSPORT_OPTIONS = {
    'region': 'ap-southeast-1a',
    'visibility_timeout': 3600,
    'polling_interval': 0.3,
    'queue_name_prefix': 'celery-',
}
BROKER_USER = AWS_ACCESS_KEY_ID
BROKER_PASSWORD = AWS_SECRET_ACCESS_KEY
# sqs://aws_access_key_id:aws_secret_access_key@
BROKER_URL = 'sqs://'+AWS_ACCESS_KEY_ID+':'+AWS_SECRET_ACCESS_KEY+'@'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'